#!/bin/bash

set -euo pipefail

if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 VERSION SHA256" >&2
    exit 64
fi

version="$1"
checksum="$2"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid version: $version" >&2
    exit 64
fi
if [[ ! "$checksum" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Invalid SHA256: $checksum" >&2
    exit 64
fi

cat <<EOF
# typed: strict
# frozen_string_literal: true

# This file was generated by the GitHub Account Switcher release workflow. DO NOT EDIT.
cask "github-account-switcher" do
  version "$version"
  sha256 "$checksum"

  url "https://github.com/mobilepur/github-account-switcher/releases/download/v#{version}/GitHub-Account-Switcher.tar.gz"
  name "GitHub Account Switcher"
  desc "Switch GitHub CLI accounts and SSH identities from the menu bar"
  homepage "https://github.com/mobilepur/github-account-switcher"

  depends_on formula: "gh"
  depends_on macos: :sonoma

  app "GitHub Account Switcher.app"
  binary "gh-switcher"

  postflight do
    [
      "#{appdir}/GitHub Account Switcher.app",
      "#{staged_path}/gh-switcher",
    ].each do |path|
      quarantine = system_command(
        "/usr/bin/xattr",
        args:         ["-p", "com.apple.quarantine", path],
        must_succeed: false,
        print_stderr: false,
      )
      next unless quarantine&.success?

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path]
    end
  end
end
EOF
